// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPssZ9syCkl4wDW1K8FFRnHCWQev3L6sI',
    appId: '1:729202495362:web:687d2491a55cbcf213c99b',
    messagingSenderId: '729202495362',
    projectId: 'ecommerce2-4d0bf',
    authDomain: 'ecommerce2-4d0bf.firebaseapp.com',
    storageBucket: 'ecommerce2-4d0bf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB42YoYs9SmBDYV-y9pzFCCAckbZEZNp4M',
    appId: '1:729202495362:android:ae45d5a6c282e0a713c99b',
    messagingSenderId: '729202495362',
    projectId: 'ecommerce2-4d0bf',
    storageBucket: 'ecommerce2-4d0bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgFMQDAi-C3wsHIdENpXSwJA6n4rV0TXo',
    appId: '1:729202495362:ios:2a9c01cd9f5968c213c99b',
    messagingSenderId: '729202495362',
    projectId: 'ecommerce2-4d0bf',
    storageBucket: 'ecommerce2-4d0bf.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgFMQDAi-C3wsHIdENpXSwJA6n4rV0TXo',
    appId: '1:729202495362:ios:2a9c01cd9f5968c213c99b',
    messagingSenderId: '729202495362',
    projectId: 'ecommerce2-4d0bf',
    storageBucket: 'ecommerce2-4d0bf.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPssZ9syCkl4wDW1K8FFRnHCWQev3L6sI',
    appId: '1:729202495362:web:19504ffdc9ca253e13c99b',
    messagingSenderId: '729202495362',
    projectId: 'ecommerce2-4d0bf',
    authDomain: 'ecommerce2-4d0bf.firebaseapp.com',
    storageBucket: 'ecommerce2-4d0bf.firebasestorage.app',
  );
}
